services:
  local_app:
    build:
      context: .
    container_name: local_app
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "${BACKEND_HOST_PORT}:${BACKEND_CONTAINER_PORT}"
    environment:
      BACKEND_HOST_PORT: ${BACKEND_HOST_PORT}
      BACKEND_CONTAINER_PORT: ${BACKEND_CONTAINER_PORT}
      DB_TYPE: ${DB_TYPE}
      DB_HOST: ${DB_HOST}
      DB_HOST_PORT: ${DB_HOST_PORT}
      DB_CONTAINER_PORT: ${DB_CONTAINER_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_HOST_PORT: ${REDIS_HOST_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      - local_db
      - local_redis
    command: ["tail", "-f", "/dev/null"]  ## for local

  local_db:
    image: postgres:16.5-alpine
    container_name: local_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_HOST_PORT}:${DB_CONTAINER_PORT}"
  
  local_redis:
    image: redis:7.4.1
    container_name: local_redis
    ports:
      - "${REDIS_HOST_PORT}:${REDIS_CONTAINER_PORT}"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
